<?php
header('HTTP/1.1 503 Service Temporarily Unavailable',true,503);
header('Status: 503 Service Temporarily Unavailable');
header('Retry-After: 172800');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Down for Maintenance</title>
</head>

<body style="margin:0; padding:0; background:black; position:relative;">

<div style="height:337px;width:442px;background:url('http://maintenance.tokidoki.it/503a.jpg') center center no-repeat;margin:200px auto 0 auto; position:relative;">
        <a href="http://www.facebook.com/Tokidoki" target="_blank" style="position:absolute;height:40px;width:40px; top:264px; left:166px;display:block;"></a>
    <a href="http://www.twitter.com/#!/tokidoki" target="_blank" style="position:absolute;height:40px;width:40px; top:264px; left:219px;display:block;"></a>
</div>
        <div style="height:337px;width:442px;margin:20px auto 0 auto;color:white; font-family:arial, helvetica, sans-serif;font-size:12px;">
<p style="text-align:center;">The tokidoki shop is down for server maintenance. We apologize for any inconvenience!</p>
        <p align="center">Please <a style="color:#eee;" href="/">click here</a> to return to tokidoki.it.</p>
</div>
</body>
</html>