---
- name: Install packages
  hosts: all
  vars:
    rsync_src: "/home/sites/tokidoki.it/shop/"
    rsync_dst: "/home/sites/tokidoki.it/shop/"
    ssh_key: "toki.pem"
    owner: "ec2-user"
    host: "ip-10-9-158-189.ec2.internal"
  tasks:

  
  - name: Install packages  
    yum: name={{ item }} state=present
    with_items:
      - httpd 
      - httpd-devel 
      - php 
      - php-xml 
      - php-mcrypt 
      - php-soap 
      - php-dba 
      - php-pecl-memcache 
      - php-devel 
      - php-mysql 
      - php-xmlrpc 
      - php-pdo 
      - php-gd 
      - php-mbstring 
      - php-pear
      - mod_ssl
      - php-pecl-apc
      - memcached
  
  handlers:
  - name: restart apache
    service: name=httpd state=restarted enabled=true

  - name: Create DocumentRoot
    file: path={{ rsync_src }} owner=ec2-user group=ec2-user mode=0775 state=directory recurse=yes

  - name: Create ansible config file
    template: src=ansible.cfg dest=/etc/ansible/ansible.cfg

  - name: Copy key
    template: src={{ ssh_key }} dest=/home/{{ owner }}.ssh/{{ ssh_key }} owner={{ owner }} group={{ owner }} mode=0600

  - name: Sync apache config over
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/etc/httpd/conf* /etc/httpd/
  
  - name: Sync php config over
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/etc/php* /etc/
  
  - name: Sync DocumentRoot
    command: rsync -az --exclude='*session*' --exclude='*cache*' -e "ssh -o StrictHostKeyChecking=no 
      -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner}}@{{ host }}:{{ rsync_src }} {{ rsync_dst}}
    notify:
      - restart apache

  - name: Set permissions
    file: path=/home/sites owner=ec2-user group=ec2-user mode=0775 state=directory recurse=yes

  - name: Start memcached
    service: name=memcached state=started enabled=true
