---
- name: Install packages
  hosts: all
  vars:
    rsync_src: "/home/sites/tokidoki.it/httpdocs/"
    rsync_dst: "/home/sites/tokidoki.it/httpdocs/"
    ssh_key: "toki.pem"
    owner: "ec2-user"
    host: "ip-10-9-158-189.ec2.internal"
    ssl_path: "/etc/ssl/certs/"
  tasks:

  
  - name: Install packages  
    yum: name={{ item }} state=present
    with_items:
      - httpd 
      - httpd-devel 
      - php 
      - php-xml 
      - php-mcrypt 
      - php-soap 
      - php-dba 
      - php-pecl-memcache 
      - php-devel 
      - php-mysql 
      - php-xmlrpc 
      - php-pdo 
      - php-gd 
      - php-mbstring 
      - php-pear
      - mod_ssl
      - php-pecl-apc
      - memcached
  

  - name: Create DocumentRoot
    file: path={{ rsync_src }} owner=ec2-user group=ec2-user mode=0775 state=directory recurse=yes

  - name: Create ansible config file
    template: src=ansible.cfg dest=/etc/ansible/ansible.cfg

  - name: Copy key
    template: src={{ ssh_key }} dest=/home/{{ owner }}/.ssh/{{ ssh_key }} owner={{ owner }} group={{ owner }} mode=0600

  - name: Sync SSL 
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" root@{{ host }}:{{ ssl_path }} {{ ssl_path }}

  - name: Sync apache config over
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/etc/httpd/conf* /etc/httpd/
  - name: Sync apc module 
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/usr/share/pear/apc.php /usr/share/pear/apc.php
  
  - name: Sync php config over
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/etc/php* /etc/
  
  - name: Sync DocumentRoot
    command: rsync -az --exclude='var/*cache*' --exclude='var/*session*' --exclude='*blog*' --exclude='*beta*' --exclude='*files*' --exclude='*shop_*' 
      -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" root@{{ host }}:{{ rsync_src }} {{ rsync_dst}}

  - name: Set permissions
    file: path=/home/sites owner=ec2-user group=ec2-user mode=0775 state=directory recurse=yes

  - name: Start memcached
    service: name=memcached state=started enabled=true

  - name: Apache config
    template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf mode=0644
    notify:
      - restart apache

  handlers:
  - name: restart apache
    service: name=httpd state=restarted enabled=true