---
- name: Install packages
  hosts: all
  vars:
    rsync_src: "/home/sites/tokidoki.it/httpdocs/"
    rsync_dst: "/home/sites/tokidoki.it/httpdocs/"
    ssh_key: "toki.pem"
    owner: "ec2-user"
    host: "ec2-54-224-126-116.compute-1.amazonaws.com"
#    ssl_path: "/etc/ssl/certs/"
    gfx_path: "/home/sites/tokidoki.it/httpdocs/gfx/"
  tasks:

  
  - name: Install packages  
    yum: name={{ item }} state=present
    with_items:
      - httpd 
      - httpd-devel 
      - php 
      - php-xml 
      - php-mcrypt 
      - php-soap 
      - php-dba 
      - php-pecl-memcache 
      - php-devel 
      - php-mysql 
      - php-xmlrpc 
      - php-pdo 
      - php-gd 
      - php-mbstring 
      - php-pear
      - mod_ssl
     # - php-pecl-apc
      - memcached
      - telnet
      - mysql
  

  - name: Create DocumentRoot
    file: path={{ rsync_src }} owner=ec2-user group=ec2-user mode=0775 state=directory recurse=yes

  - name: Create ansible config file
    template: src=ansible.cfg dest=/etc/ansible/ansible.cfg

  - name: Create cron file
    template: src=root_cron dest=/var/spool/cron/root

  - name: Copy key
    template: src={{ ssh_key }} dest=/home/{{ owner }}/.ssh/{{ ssh_key }} owner={{ owner }} group={{ owner }} mode=0600

  - name: Sync apache config over
    command: rsync -az --exclude='*ssl*' -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/etc/httpd/conf* /etc/httpd/

#  - name: Sync apc module 
#    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/usr/share/pear/apc.php /usr/share/pear/apc.php
  
  - name: Sync php config over
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:/etc/php* /etc/
  
  - name: Sync gfx
    command: rsync -az -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" {{ owner }}@{{ host }}:{{ gfx_path }} {{ gfx_path }}

  - name: Sync DocumentRoot
    command: rsync -az --exclude='var/cache' --exclude='var/full_page_cache' --exclude='var/session' 
      -e "ssh -o StrictHostKeyChecking=no -i /home/{{ owner }}/.ssh/{{ ssh_key }}" root@{{ host }}:{{ rsync_src }} {{ rsync_dst}}

  - name: Create cache dirs
    file: path={{ rsync_src }}/shop/var/{{ item }} owner=ec2-user group=ec2-user mode=0775 state=directory recurse=yes
    with_items:
      - cache
      - full_page_cache
      - session

  - name: Set permissions
    file: path=/home/sites owner=ec2-user group=ec2-user mode=0775 state=directory recurse=yes

  - name: Start memcached
    service: name=memcached state=started enabled=true

  - name: symlink maintenance dir
    file: src={{ rsync_dst }}/maintenance dest={{ rsync_dst }}/shop/maintenance owner=ec2-user group=ec2-user state=link recurse=yes

  - name: Apache config
    template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf mode=0644
    notify:
      - restart apache

  - name: Magento index.php
    template: src=shop_index dest={{ rsync_dst }}/shop/index.php


  handlers:
  - name: restart apache
    service: name=httpd state=restarted enabled=true