---
- name: Install packages
  hosts: all
  tasks:

  - name: Install packages  
    yum: name={{ item }} state=present
    with_items:
      - httpd 
      - httpd-devel 
      - php 
      - php-xml 
      - php-mcrypt 
      - php-soap 
      - php-dba 
      - php-pecl-memcache 
      - php-devel 
      - php-mysql 
      - php-xmlrpc 
      - php-pdo 
      - php-gd 
      - php-mbstring 
      - php-pear
      - mod_ssl
      - php-pecl-apc
      - memcached

  - name: Create DocumentRoot
    file: path=/home/sites/tokidoki.it/httpdocs/shop owner=ec2-user group=ec2-user mode=0775 state=directory

  - name: Copy key
    template: src=toki.pem dest=/home/ec2-user/.ssh/toki.pem owner=ec2-user group=ec2-user mode=0600

  - name: Sync apache config over
    command: rsync -ahW --no-compress ec2-user@ip-10-9-158-189.ec2.internal:/etc/httpd/conf* /etc/httpd/
  
  - name: Sync php config over
    command: rsync -ahW --no-compress ec2-user@ip-10-9-158-189.ec2.internal:/etc/php* /etc/
  
  - name: Sync DocumentRoot
    command: rsync -ahW --no-compress ec2-user@ip-10-9-158-189.ec2.internal:/home/sites/tokidoki.it/httpdocs/shop/ /home/sites/tokidoki.it/httpdocs/shop/

  - name: Restart Apache
    service: name=httpd state=started enabled=true